# Generated by Django 2.2.3 on 2019-07-07 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='img',
            field=models.ImageField(default='/static/img/default.jpg', max_length=255, upload_to=''),
        ),
        migrations.AlterField(
            model_name='good',
            name='img',
            field=models.ImageField(default='/static/img/default.jpg', max_length=255, upload_to=''),
        ),
    ]
