# Generated by Django 2.2.3 on 2019-07-07 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20190707_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='img',
            field=models.ImageField(default='/static/img/default.jpg', max_length=255, upload_to='./static/goods'),
        ),
    ]
