# Generated by Django 2.2.3 on 2019-07-07 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20190707_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='img',
            field=models.ImageField(default='/static/img/default.jpg', max_length=255, upload_to='./static/img/brands'),
        ),
        migrations.AlterField(
            model_name='good',
            name='img',
            field=models.ImageField(default='/static/img/default.jpg', max_length=255, upload_to='./static/img/goods'),
        ),
        migrations.AlterField(
            model_name='good',
            name='ram',
            field=models.CharField(default='4', max_length=32),
        ),
        migrations.AlterField(
            model_name='good',
            name='rom',
            field=models.CharField(default='16', max_length=32),
        ),
    ]
