# Generated by Django 2.2.3 on 2019-07-07 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_auto_20190707_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='feature',
            field=models.CharField(max_length=255),
        ),
    ]
