# Generated by Django 2.2.3 on 2019-07-07 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_auto_20190707_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='network',
            field=models.CharField(default='全网通', max_length=32),
        ),
    ]
