# Generated by Django 2.2.3 on 2019-07-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_auto_20190707_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='desc',
            field=models.CharField(default='', max_length=512),
        ),
    ]
