# Generated by Django 2.2.3 on 2019-07-12 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='color',
            field=models.CharField(default='黑色', max_length=32),
        ),
        migrations.AddField(
            model_name='cart',
            name='ram',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='cart',
            name='rom',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='cname',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='ename',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
