# Generated by Django 2.2.3 on 2019-07-12 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_auto_20190712_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='ram',
            field=models.IntegerField(),
        ),
    ]
