# Generated by Django 2.2.3 on 2019-07-12 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_auto_20190712_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='price',
            field=models.FloatField(default=1),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=255, unique=True)),
                ('order_create', models.DateTimeField(auto_now_add=True)),
                ('order_price', models.FloatField(default=0)),
                ('order_status', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.User')),
            ],
        ),
    ]
