# Generated by Django 2.2.3 on 2019-07-12 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_auto_20190712_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('color', models.CharField(default='黑色', max_length=32)),
                ('ram', models.IntegerField(default=8)),
                ('rom', models.IntegerField(default=128)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Good')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Order')),
            ],
        ),
    ]
