# Generated by Django 2.2.3 on 2019-07-14 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_ordergoods'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=32)),
                ('phone', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.User')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='receive_info',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='App.Receive'),
        ),
    ]
