# Generated by Django 2.2.3 on 2019-07-14 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0015_auto_20190714_1759'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='receive_info',
            new_name='receive',
        ),
    ]
