# Generated by Django 2.2.3 on 2019-07-16 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0017_auto_20190714_2337'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloorGood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('name', models.CharField(max_length=128)),
                ('desc', models.CharField(max_length=255)),
                ('price', models.IntegerField(default=0, max_length=20)),
                ('img', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.CharField(max_length=255)),
                ('img2', models.CharField(max_length=255)),
                ('good1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='good1', to='App.FloorGood')),
                ('good2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='good2', to='App.FloorGood')),
                ('good3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='good3', to='App.FloorGood')),
                ('good4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='good4', to='App.FloorGood')),
                ('good5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='good5', to='App.FloorGood')),
                ('good6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='good6', to='App.FloorGood')),
            ],
        ),
    ]
