# Generated by Django 2.2.3 on 2019-07-16 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0020_banner_lun'),
    ]

    operations = [
        migrations.RenameField(
            model_name='floorgood',
            old_name='name',
            new_name='a',
        ),
        migrations.RenameField(
            model_name='floorgood',
            old_name='desc',
            new_name='p',
        ),
    ]
