# Generated by Django 2.2.3 on 2019-07-16 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0021_auto_20190716_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tuan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=255)),
            ],
        ),
    ]
