# Generated by Django 2.2.3 on 2019-07-16 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0022_tuan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='floor',
            old_name='img1',
            new_name='img',
        ),
    ]
