# Generated by Django 2.2.3 on 2019-07-16 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0023_auto_20190716_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='floor',
            name='good1',
        ),
        migrations.RemoveField(
            model_name='floor',
            name='good2',
        ),
        migrations.RemoveField(
            model_name='floor',
            name='good3',
        ),
        migrations.RemoveField(
            model_name='floor',
            name='good4',
        ),
        migrations.RemoveField(
            model_name='floor',
            name='good5',
        ),
        migrations.RemoveField(
            model_name='floor',
            name='good6',
        ),
        migrations.AddField(
            model_name='floorgood',
            name='floor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='App.Floor'),
        ),
    ]
