# Generated by Django 2.2.3 on 2019-07-16 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0025_auto_20190716_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='floorgood',
            name='product_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='floorgood',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
