# Generated by Django 2.2.3 on 2019-07-17 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0026_auto_20190716_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='AncestralType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='ParentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('ancestral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.AncestralType')),
            ],
        ),
        migrations.AddField(
            model_name='good',
            name='parent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='App.ParentType'),
            preserve_default=False,
        ),
    ]
