# Generated by Django 2.2.3 on 2019-07-17 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0027_auto_20190717_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parenttype',
            name='ancestral',
        ),
        migrations.DeleteModel(
            name='AncestralType',
        ),
    ]
