# Generated by Django 2.2.3 on 2019-07-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0028_auto_20190717_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='AncestralType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
    ]
