# Generated by Django 2.2.3 on 2019-07-17 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0031_auto_20190717_1757'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrotherType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('grand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.ParentType')),
            ],
        ),
        migrations.AlterField(
            model_name='good',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.BrotherType'),
        ),
    ]
