# Generated by Django 2.2.3 on 2019-07-17 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0033_auto_20190717_1915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brothertype',
            old_name='grand',
            new_name='parent',
        ),
    ]
